core/PRP/Physics/plGenericPhysical.cpp
Fixes the bug previously worked around by https://github.com/H-uru/Plasma/pull/347
As discussed in that PR, PyPRP exports restitution values which are invalid for PhysX physicals.  This change ensures that the library doesn't just pass along these bad values.
=> Clamp restitution values to valid range.

Python/Stream/pyEncryptedStream.cpp, Python/Stream/pyFileStream.cpp
This implements the `__enter__` and `__exit__` methods required for` with` context management support. This implementation matches what I saw in Python 3.4's iobase.c.
In case you're unfamiliar, this allows us to write nice, pythonic code...
```python
with plEncryptedStream(pvMoul).open("sample.age", fmWrite, plEncryptedStream.kEncXtea) as moo:
moo.writeLine("something")
```
instead of a `try`... `finally` thing.
=> pyFileStream and pyEncryptedStream with statements

Python/PRP/Geometry/pyGeometrySpan.cpp, core/PRP/Geometry/plDrawableSpans.cpp, core/PRP/Geometry/plGeometrySpan.h, core/PRP/Geometry/plSpan.h
`plGeometrySpan` now knows about the PermaLights and PermaProjections, just like the actual spans do. This includes Python bindings and compose/decompose support. I know that this is not 1:1 with what Plasma does, but it's easier IME to deal with RT lights here instead of after the fact.
=> GeoSpan + RT Lights

core/PRP/Geometry/plVertCoder.cpp
This fixes an issue with vertex color encoding/decoding introduced by 5d4496e. The colors were swapped in what appears to be an attempt to replicate some unused debug bit shifting. Probably under the assumption that input data is RGBA (Plasma expects BGRA). However input data is assumed to be BGRA, as that is what `hsColor32` uses under the hood.
This issue was not noticed when testing transfused ages (which had previous issues with green vertex colors) because the bug was introduced in both the encode and decode routines, which means there was actually no net change to ages that were simply read in and written out.
=> Fix vcol color space issue

Python/CMakeLists.txt, Python/Module.cpp, Python/PRP/Avatar/pySittingModifier.cpp, Python/PRP/Avatar/pySittingModifier.h, Python/PRP/Message/pyCursorChangeMsg.cpp, Python/PRP/Message/pyCursorChangeMsg.h, Python/PRP/pyCreatableConvert.cpp, core/CMakeLists.txt, core/PRP/Avatar/plSittingModifier.h, core/PRP/Message/plCursorChangeMsg.cpp, core/PRP/Message/plCursorChangeMsg.h, core/ResManager/plFactory.cpp
This implements everything needed to have an epic sitting modifier in Python. As a bonus, plCursorChangeMsg is now implemented, which contains the enum for the cursor states. AFAIK, these shouldn't be in any Cyan age.
=> Sitting Modifiers and Cursors

Python/CMakeLists.txt, Python/Module.cpp, Python/PRP/Animation/pyCompoundController.cpp, Python/PRP/Animation/pyCompoundPosController.cpp, Python/PRP/Animation/pyCompoundRotController.cpp, Python/PRP/Animation/pyLeafController.cpp, Python/PRP/Animation/pyTMController.cpp, Python/PRP/Avatar/pyAGAnim.cpp, Python/PRP/Avatar/pyAGApplicator.cpp, Python/PRP/Avatar/pyAGChannel.cpp, Python/PRP/Avatar/pyAGMasterMod.cpp, Python/PRP/Avatar/pyAGMasterMod.h, Python/PRP/Avatar/pyAGModifier.cpp, Python/PRP/Avatar/pyAGModifier.h, Python/PRP/Avatar/pyATCAnim.cpp, Python/PRP/Avatar/pyMatrixChannel.cpp, Python/PRP/Avatar/pyMatrixControllerChannel.cpp, Python/PRP/pyCreatableConvert.cpp, core/PRP/Animation/plLeafController.cpp, core/PRP/Avatar/plAGMasterMod.h, core/PRP/Avatar/plAGModifier.h
Improves the animation bits of PyHSPlasma by adding correct duck-typing for many return values and fixes many of those pesky plCreatable casts. This doesn't fix every single problem in the land, but it hits all of the ones needed for exporting simple animations in Korman and then some :smile:.
=> PyHSPlasma Animation Improvements

Python/Stream/pyEncryptedStream.cpp, Python/Stream/pyFileStream.cpp, Python/Stream/pyRAMStream.cpp, Python/Stream/pyStream.cpp, core/Stream/hsStream.h
I know this doesn't match the C++ API, but it seems more pythonic to be able to write:
```python
stream.close()
```
as a catch-all instead of
```python
if isinstance(stream, hsFileStream):
stream.close()
```
when you're juggling both hsFileStream and hsRAMStream.
=> Add a stub for pyRAMStream.close()

CMakeLists.txt, Python/CMakeLists.txt, core/CMakeLists.txt, net/CMakeLists.txt
Added an option to build static libraries. (or rather, added an option to build shared libs, and set it to default on)
Also, I built this with MinGW 4.9.2, and it requires a newer std flag, or else it complains about some of the Win32 includes. Using gnu++11 shouldn't cause issues with other gcc environments, but it may be worth checking, especially given that mismatching this flag _will_ cause linking issues.
=> Static build

Python/CMakeLists.txt
Without this patch, I am getting an error, the interpreter search complaining that there is no version '2.7.10+'. I have no idea who thought it was a good idea to make *that* the version number returned by the library search.
=> Deal with python library version '2.7.10+'

CMakeLists.txt, core/CMakeLists.txt
Allows building without linking to PhysX even on systems that have the SDK available and detected.
=> Add CMake option to allow building without PhysX support.

CMakeLists.txt, Python/PyPlasma.h, cmake/PlasmaConfig.h.in, cmake/check_size_t_overload.cpp
Fix platforms where size_t is typedeffed differently from uint##_t (e.g. Mac)
=> Fix for size_t overloading

Python/CMakeLists.txt, Python/Module.cpp, Python/PRP/Avatar/pyLadderModifier.cpp, Python/PRP/Avatar/pyLadderModifier.h, Python/PRP/pyCreatableConvert.cpp, core/PRP/Avatar/plLadderModifier.h
This adds missing functions in `plAvLadderMod` and `plLadderModifier`, as well as their Python bindings.
=> Add bindings for plAvLadderMod and plLadderModifier.

CMakeLists.txt, core/Stream/hsStream.cpp
This allows libhsplasma to load PRPs with Latin-1 encoded strings (see #97).
Note that doing so and then re-saving the PRP will cause the string to get converted to UTF-8, which **may break external references** if they are not also updated to UTF-8.
=> Latin-1 PRP support

net/CMakeLists.txt, net/crypt/pnSha1.cpp
Dynamically detect available SHA algorithms and throw an exception when one isn't available (fixes compilation but not functionality with current OpenSSL versions that removed SHA0).  This also ports to the more standard/supported (albeit more verbose) EVP APIs instead of direct calls to the low-level SHA algorithms.
=> Dynamically detect available SHA algorithms and port to EVP APIs

core/PRP/plPageInfo.cpp
Previously, the plPageInfo writer passed a mapped creatable ID to pdUnifiedTypeMap to retrieve the class version. This was inappropriate as that function expected a plasma specific creatable ID. Due to the shared nature of the creatable IDs and tendency of them to be zero, this went unnoticed until I tried writing an esoteric creatable plRidingAnimatedPhysicalDetector, which was given a class version of -1
=> Fix class version writing

core/Stream/pfPrcHelper.cpp, core/Stream/pfPrcHelper.h
#107 changed the way the maximum number of emitters was stored such that it now has a type of size_t. On x64, this is a 64-bit integer for which there was no 64-bit PRC overload. This adds a 64-bit overload in the style of the already existing ones such that libHSPlasma will compile again.
=> Fix 64-bit build

Python/Util/pyDDSurface.cpp
DDSurface::createMipmap returns raw plMipmaps with uninitialized KeyedObjects, leaving them partially unusable in PyHSPlasma scripts.  This adds the KeyedObject init to the function's Python binding.
=> Fix unusable pyMipmaps from DDSurfaces.

Python/PRP/Message/pyCameraMsg.cpp
One of the very few konstants in this message that is actually used was missing 😿
=> Add missing camera constant to PyHSPlasma

Python/PRP/Geometry/pyDrawableSpans.cpp, Python/PRP/Geometry/pyGeometrySpan.cpp, Python/PRP/Geometry/pyGeometrySpan.h, core/PRP/Geometry/plDrawableSpans.cpp, core/PRP/Geometry/plDrawableSpans.h
This did not match the rest of PyHSPlasma and caused some odd crashes when trying to access a DrawableSpan's sourceSpans from Python.
=> Remove smart pointers from pyGeometrySpan

core/Util/plPNG.cpp
This fix corrects the color channel order of PNGs to match that used by [Plasma](https://github.com/H-uru/Plasma).  During testing of https://github.com/H-uru/korman/pull/103, it was discovered that the answer is seemingly "yes, HSPlasma does need this".
=> Fix PNG channel order for reading and writing.

Python/PyPlasma.cpp, core/PRP/KeyedObject/hsKeyedObject.h, core/PRP/KeyedObject/plKey.h, core/PRP/plCreatable.h, core/PlasmaDefs.h
* Make `plKey` non-virtual and final
* Optimize conversion of Python strings to `ST::string`
* Rename some macros for clarity
=> Minor cleanup and optimizations

Python/PRP/Surface/pyMipmap.cpp, Python/PyPlasma.h
This changeset adds more exception translators to the `pyMipmap` member functions and removes some redundant buffer copying.
=> pyMipmap improvements

Python/Stream/pyRAMStream.cpp, Python/Stream/pyStream.cpp
This removes a few more temporary heap-allocated buffers from PyHSPlasma's hsStream bindings. The buffers are replaced with using the final PyBytes objects' backing buffers.
=> Remove more temporary heap buffers from PyHSPlasma

core/Debug/hsExceptions.hpp, core/SDL/plSDLMgr.cpp, core/SDL/plSDLMgr.h, core/Stream/hsStream.cpp, core/Stream/hsStream.h, core/Stream/pfPrcParser.cpp, core/Stream/pfPrcParser.h, core/Util/plJPEG.cpp, core/Util/plJPEG.h, core/Util/plPNG.cpp, core/Util/plPNG.h
Also makes better use of ST literals in exception messages.
=> Inline exception classes to silence "class derived from non-dllexport base" warnings in MSVC 2017

.travis.yml, CMakeLists.txt, appveyor.yml, core/PlasmaDefs.h
and remove MSVC stdint.h hack that hasn't been needed since VS2010.
=> Use newer CMake with built-in compiler flag settings for C++ standard,

Tools/src/PrpPack.cpp
Fixes a crash caused by invalid file handles when the expected input folder is missing or empty.
=> Fix PrpPack crash on empty input folder.

Python/Debug/pyDebug.cpp, Python/PRP/Audio/pySoundBuffer.cpp, Python/PRP/Avatar/pyAGAnimBink.cpp, Python/PRP/Modifier/pyPythonFileMod.cpp, Python/PRP/Surface/pyLayerMovie.cpp, Python/PyPlasma.cpp, Python/PyPlasma.h, Python/ResManager/pyAgeInfo.cpp, Python/ResManager/pyPageInfo.cpp, Python/ResManager/pyResManager.cpp, Python/SDL/pySDLMgr.cpp, Python/Stream/pyEncryptedStream.cpp, Python/Stream/pyFileStream.cpp, core/Debug/plDebug.cpp, core/Debug/plDebug.h
This changeset adds support for the `os.PathLike` protocol added in Python 3.6 for any properties or function arguments that expect anything resembling a path or a filename. This allows us to pass `pathlib.Path` objects seemlessly to libHSPlasma in Python 3.6+. CPython seems to use `PyUnicode_FSDecoder` instead of manually calling the `__fspath__` method, so that is the approach I took. Unfortunately, In lower versioned Python 3.5 and lower, it is still required to convert path objects to their string representations before passing them to libHSPlasma.
This closes #148
=> Support `os.PathLike` for paths and filenames.

net/CMakeLists.txt
This fixes linking with OpenSSL 1.1.1 on Windows.
=> Add missing OpenSSL linker dependency.

Python/Stream/pyEncryptedStream.cpp
This fixes a crash encountered by Doobes when Korman thought it was a good idea to use `plEncryptedStream.IsFileEncrypted` on a directory path.
=> Fix crash in `pyEncryptedStream.IsFileEncrypted`.

.github/workflows/macos-ci.yml, CMakeLists.txt
This also fixes a leftover hard-coded `-stdlib` clang parameter that should be automatically applied by CMake's `CMAKE_CXX_STANDARD` setting.
=> Support GCC on macOS CI builds

core/ResManager/plAgeInfo.cpp
This fixes a crash in libHSPlasma when reading in the spyroom.age file shipped with MOULa. The file has empty lines separating each content line.
=> Don't process blank lines in an age file.

Python/PRP/Geometry/pyDrawableSpans.cpp, Python/PRP/Geometry/pyGeometrySpan.cpp, core/PRP/Geometry/plDrawableSpans.cpp, core/PRP/Geometry/plDrawableSpans.h, core/PRP/Geometry/plGBufferGroup.cpp, core/PRP/Geometry/plGBufferGroup.h, core/PRP/Geometry/plGeometrySpan.cpp, core/PRP/Geometry/plGeometrySpan.h
This changeset optimizes the output of `plDrawableSpans::composeGeometry` by attempting to pack spans into a one vertex buffer in plGBufferGroup. These vertex buffers correspond to DirectX vertex buffers in Plasma. There are many buffer group formats in Plasma, and the code attempts to not obliterate anything another user of the buffer group has done.
This also fixes an issue in which the index data of a `plGeometrySpan` could be lost if the number of indices changed after being initialized or set by IO.
=> Pack DSpan GeoSpans into single vertex buffer.

core/PRP/Geometry/plGBufferGroup.cpp
This was a compile error for me, but I don't know how the CI builds somehow managed to not hit this :man_shrugging:
=> Fix missing cstring include for memcpy

Python/PRP/Animation/pyKeys.h, Python/PRP/Animation/pyLeafController.cpp
Returning the `.keys` of a plLeafController in Python would return a tuple containing an array of hsKeyFrames. In reality, that should be an array of the specific hsKeyFrame subclasses.
/cc @Jrius This should resolve the need for haxKeyFrames in ZLZ
=> Return pyKeyFrames as the correct subtype

core/Stream/hsStream.cpp
Some files (only `spyroom.age` AFAIK) use MacOS `\r` line endings, which cause `hsStream::readLine()` to fail as it assumes those are followed by a `\n` character. This fixes that.
=> Support MacOS newlines in hsStream

Python/PRP/Geometry/pyDrawableSpans.cpp, core/PRP/Geometry/plDrawableSpans.cpp, core/PRP/Geometry/plDrawableSpans.h
We need this index so that we can point our `kMatrixOnly` DISpanIndices to the correct transform index.
=> Return the index when adding DSpan bone transforms

Python/PRP/Region/pyConvexIsect.cpp, Python/PRP/Region/pyVolumeIsect.h, core/PRP/Region/plVolumeIsect.cpp, core/PRP/Region/plVolumeIsect.h
Needed to add support for softvolumes in ZLZ, figured it would be a good time to finally get familiar with writing Python bindings...
Allows accessing the list of planes of a `plConvexIsect`, and retrieve each plane's position, normal, etc.
This is heavily inspired by the bindings for the very similar `plCameraModifier::CamTrans` class. It required making `SinglePlane`'s fields protected and add getter/setter methods, and move some of the PRC read/write logic from `plConvexIsect` into `SinglePlane`.
=> Add plConvexIsect::SinglePlane python bindings

CMakeLists.txt, Python/CMakeLists.txt, Tools/CMakeLists.txt, core/CMakeLists.txt, core/HSPlasmaConfig.cmake, core/HSPlasmaConfig.cmake.in, net/CMakeLists.txt, net/HSPlasmaNetConfig.cmake, net/HSPlasmaNetConfig.cmake.in
When working on the Microsoft/vcpkg#13174, I discovered that libHSPlasma's cmake config broke when vcpkg attempted to move it to another directory. vcpkg does some peculiar string replacements that depend on our using more modern cmake standards.
Bonuses:
- linking with the HSPlasma target now brings in the include directories for you.
- compile with `/bigobj` on MSVC due to compile errors exposed by vcpkg's CI with plFactory on x64-windows.
=> Cmake modernization for vcpkg port.

core/PRP/Modifier/plPythonFileMod.cpp
This fixes an issue in which PythonFileMods with string parameters would be shattered by round-tripping through HSPlasma. The spurious null terminator was being accumulated into the parameter, causing two nulls to be serialized. This caused a null byte to be passed to CWE's Python, resulting in a difficult to debug scenario where we had a seemingly valid string object in Python but the validation in `PyArg_ParseTuple` failed.
To reproduce this issue, load and save Neighborhood_District_nb01.prp in libHSPlasma, then visit the Age in CWE. The resulting error output will look [something like this](https://gist.github.com/Hoikas/4bc4e48b61a0ec89dee7a7ee72a37d57).
=> Fix round-tripping plPythonFileMod through HSPlasma.

Tools/src/PlasmaSum.cpp, Tools/src/prpgrep.cpp, core/Debug/hsExceptions.hpp, core/PRP/GUI/pfGUITextBoxMod.cpp, core/PRP/Misc/plAgeLinkInfo.cpp, core/PRP/Modifier/plPythonFileMod.cpp, core/Stream/hsStream.cpp, core/Stream/hsTokenStream.cpp, net/auth/pnVaultNode.cpp
NOTE: Intentionally not using `clear()` since that would require an increase of the minimum string_theory version to 3.4.
=> Clean up uses of the recently deprecated ST::null and ST::null_t

.github/workflows/windows-ci.yml, appveyor.yml, vcpkg.json
This adds a vcpkg manifest so there is less need to rely on the old PlasmaPrefix libs and to better enable adding/removing dependencies. I omitted `python3` from the manifest because vcpkg does not integrate with the deprecated `FindPythonLibs` and `FindPythonInterp` modules. I have also moved the "modern" Visual Studio compilers from AppVeyor to GHA to improve CI parallelism. The older compilers/pythons remain on AppVeyor.
Currently, there is still interest in Visual Studio 2013 and Python 3.5 because that is what Blender 2.79b is using on Windows.
~~Still TODO: switch AppVeyor over to using the vcpkg manifest.~~
=> Add a vcpkg manifest.

core/PRP/Physics/plGenericPhysical.cpp, core/PRP/Region/hsBounds.cpp, core/PRP/Region/hsBounds.h
Found this bug when exporting Ages with Korman. Apparently, the PotS client will crash if box colliders don't have both vertices AND indices (strange, I know...)
=> Box bounds: generate indices for PotS/Havok

core/Debug/hsExceptions.hpp, core/PRP/Geometry/plCullPoly.h
Clang (rightfully) warns when a class has a copy constructor but no copy `operator=()` or vice versa.  In these specific cases, the default generated version is sufficient (and for the case of `hsException`, the manually specified version missed copying some fields).
=> Remove a couple of unnecessary copy constructors/operators.

.github/workflows/windows-ci.yml, CMakeLists.txt, Python/Sys/pyColor.h, core/CMakeLists.txt, core/Math/hsMatrix33.cpp, core/Math/hsMatrix44.cpp, core/PRP/Message/plConsoleMsg.h, core/PRP/Physics/plPXPhysical.h, core/PRP/Surface/plLayer.h, core/Util/plMD5.h, net/auth/AuthMessages.h, net/file/FileMessages.h, net/game/GameMessages.h, net/gate/GateKeeperMessages.h
Unity builds bring the MSBuild time to build all of libHSPlasma down to 2m 7s on my machine. The majority of the issues uncovered are faulty (or missing) include guards.
=> Fix and test unity builds

core/PRP/Geometry/plDrawableSpans.cpp, core/PRP/Geometry/plDrawableSpans.h, core/PRP/Physics/plGenericPhysical.cpp, core/PRP/Region/hsBounds.cpp, core/PRP/Region/hsBounds.h
PotS box bounds again. Generating the vertices/indices creates a box with face normals pointing inwards. Apparently doesn't bother PotS, but looks ugly once reimported in Blender. Fixed by reordering face indices.
Additionally, the algorithm to calculate corner vertices didn't support boxes that didn't encompass the world origin `(0, 0, 0)` due to a small initialization error, which resulted in one of the corner being placed at world origin. This fixes that too.
(If you want to see the wrongly generated vertices without this fix, paste the following code in a Python terminal. The generated box will be wrongly sized to encompass world origin.)
```
import PyHSPlasma as pl
gp = pl.plGenericPhysical()
gp.calcBoxBounds([pl.hsVector3(-1, -1, -1), pl.hsVector3(-.5,-.5, -.5)])
print(gp.verts)
```
=> Pots boxphys offcentered vertices

Python/PRP/Modifier/pyRandomSoundMod.cpp
This doesn't appear to break anything, but it causes several warnings to be emitted on newer GCC versions.
=> Fix incorrect terminator in pyRandomSoundModGroup getset list

core/ResManager/plKeyCollector.cpp, core/Stream/pfSizedStream.cpp, core/Stream/pfSizedStream.h
I tested this by loading the Garrison.age from MOULa. In the beginning, loading Garrison took approximately 34 seconds. After these changes, the time is down to approximately 6.5 seconds to load the Age. The major improvement comes from bypassing many calls to `ftell()`, which tank the performance on Windows. The downside is that this makes `pfSizedStream` a bit less flexible in that it assumes that it owns the underlying base stream and no one else will touch it while it lives.
Benchmark tool I used can be found [here](https://github.com/Hoikas/libhsplasma_bench).
=> Improve PRP read performance.

core/PRP/Animation/hsKeys.cpp
Doobes reported that animations imported from EoA by ZLZ were too fast. Apparently this is caused by this very simple typo (confusion between frame time and frame number).
You can quickly check the current wrong behavior by viewing the PRC for any ATC anim from `Direbo_RestAge.prp` in PrpShop. Most keyframes overlap.
=> Fix EoA animation timing

core/ResManager/plKeyCollector.cpp, core/ResManager/plResManager.cpp
This PR is born of finding that, in certain circumstances, loading and saving the entire Kadish Age with libHSPlasma would crash CWE either on initial load or on unload. The circumstances of the load/save was effectively an arbitrarily ordered set of calls to `ReadPage()` and `WritePage()` (specifically, not using `ReadAge()`).
libHSPlasma unconditionally sets the ObjID for each keyed object when it writes that object to a PRP to `position in key collector + 1`. This reveals some assumptions:
- all PRP keyrings are maintained in order of their obj ID
- no ObjIDs are skipped in the set of objects contained in each PRP.
Unfortunately, these assumptions are demonstrably false. For example, if you open an Age in PRPShop and resave just the Textures PRP, the object IDs will change, shattering …
=> Fix insidious ObjID issues.

core/PRP/Animation/hsKeys.cpp
This matches the implementation used by Plasma: https://github.com/H-uru/Plasma/blob/c23a4116ca6c668689e194c8cddcc02641471e32/Sources/Plasma/PubUtilLib/plInterp/hsKeys.cpp#L316-L440
I've tested that after this change the values that I see for keyframes in PRC make more sense in terms of real-world values, but also that roundtripping an animation through prcdc/prcc/prcdc yields the same result (caveat floating point rounding).
=> Fix hsCompressedQuatKey64 reading/writing

net/auth/AuthMessages.cpp, net/auth/AuthMessages.h, net/auth/pnAuthClient.cpp, net/auth/pnAuthClient.h
libhsplasmanet is missing three messages from H-uru/Plasma: kCli2Auth_ScoreGetHighScores, kAuth2Cli_ScoreGetHighScoresReply and kAuth2Cli_ServerCaps. The later one in particular prevents it from connecting to dirtsand servers, breaking tools like MoulKI. This MR implements all three, which fixes the issue.
=> Add missing server messages

core/PRP/Geometry/plSpan.cpp, core/PRP/Geometry/plSpan.h
=> Automatically manage "has PermaLight/PermaProj" property when modifying PermaLight and PermaProj vectors on spans.

.github/workflows/windows-ci.yml
The windows-2016 runner will be removed in just a few short months. To retain CI coverage with VS 2017, I've changed those jobs to use VS 2019 but with the v141 toolset. Additionally, I've added a new job for VS 2022 and Python 3.10.
=> Remove windows-2016 runner from CI.

core/CMakeLists.txt, core/Stream/hsStream.cpp, core/Stream/hsStream.h, core/Sys/Platform.h
When developing Korman's "Test Age" feature, I noticed a curious bug that I could never quite understand. The feature basically uses `hsFileStream` to modify the TPotS vault.dat, then launches Uru. Occassionally, however, Uru would act as if the changes to the vault were not made - but according to VaultShop, the changes were present! I discovered that adding [a small sleep](https://github.com/H-uru/korman/blob/1e198a1cfe725bceaa090ee3f910608cce97f1e9/korman/plasma_launcher.py#L177:L178) between writing vault.dat and launching Uru made the process slightly more reliable, but still not 100%.
As it turns out, the C file API in Windows is evidentally vulnerable to race conditions where changes are not flushed out as expected. I'm not mthe only one to discover this problem: …
=> Use Win32 API in `hsFileStream`.

Python/PRP/Geometry/pyGBufferGroup.cpp
Almost ten years later, I found the reason for #23. An argument was missing due to a simple oversight.
=> Fix pyGBufferGroup.getVertices (#23)

Python/PRP/Geometry/pySpanTemplate.cpp, Python/PRP/Geometry/pySpanTemplate.h, Python/PRP/Geometry/pySpanTemplateVertex.cpp
For some reason `pySpanTemplateVertex` (a Python reference type) sometimes becomes corrupted, which means position, normal etc get filled with junk data. I'm not sure why.
`pyGBufferVertex` which is very similar is a value type. Making `pySpanTemplateVertex` a value type solves that corruption problem on top of being more consistent. :shrug:
(`pySpanTemplateVertex` is used by cluster groups - which ZLZ can now import.)
=> Python: make pySpanTemplateVertex a value type

Python/Module.cpp
libHSPlasma has been configured to use proper symbol visibility, which has resulted in all of the PyHSPlasma symbols being marked hidden.
`PyMODINIT_FUNC` on Python 3.9+ has been updated to include visibility annotations, but on earlier versions it is missing.
I've confirmed this is working for me when building for Python 3.7.
Closes #248
=> Fix for PyInit_PyHSPlasma visibility on Py <3.9

Python/Math/pyQuat.cpp, core/Math/hsQuat.h
We prefer to initialize things to a state that is somewhat valid. Therefore, initialize to an identity quaternion instead of a zero (read: illegal) quaternion.
=> Improve hsQuat initialization.

CMakeLists.txt
This should fix #260. [`check_cxx_compiler_flag()`](https://cmake.org/cmake/help/latest/module/CheckCXXCompilerFlag.html) actually tries to compile a dummy file, so the check should fail on ARM targets. This also hides the bogus `ENABLE_SSE2` option when the compiler is MSVC.
=> Only use the SSE2 flag when it's supported by the compiler.

Tools/src/prcc.cpp, Tools/src/prcdc.cpp, core/PRP/KeyedObject/plUoid.cpp, core/ResManager/plResManager.cpp, core/ResManager/plResManager.h
After several attempts to address issues around Object ID mismatches, we've adopted a stance of libHSPlasma reassigning all Object IDs on read. This generally works okay (with caveats around cross-page references) but causes problems if you're wanting to round-trip data through libHSPlasma without modifying it.
This adds a `preserveObjectIDs()` method to plResManager that tells it not to change object IDs when reading. This is **not safe** if you are adding or removing any objects from the PRP file, but should be safe if you're only wanting to edit some object data.
This also sets up the `prcdc` tool to always dump out the original Object IDs to get an accurate view of the data.
When running `prcc` to compile from PRC files, there's a new `--keep-ids` option to use the object ID values as …
=> Add ResMgr option to preserve Object IDs

core/ResManager/plResManager.cpp
Scan beyond just the first page in a .age file when determining what naming convention to use for opening pages.
This fixes the case when the first page in the .age file doesn't exist, which fixes H-uru/PlasmaShop#71
=> Fix loading .age files where the first page doesn't exist.

.github/workflows/windows-ci.yml, Python/CMakeLists.txt, appveyor.yml
To facilitate the writing of a vcpkg port, this updates the PyHSPlasma CMake to use the FindPython module from CMake 3.12. The previously used module has since been deprecated. To manually specify artifacts from a specific python version, set the keys `Python_INCLUDE_DIR` and `Python_LIBRARY`. Note the casing has changed from `PYTHON` (deprecated) to `Python`.
I think these changes were previously included in #166, but the ability to manually specify the artifacts did not land until CMake 3.16.
=> Use FindPython from CMake 3.12.

Tools/CMakeLists.txt, core/CMakeLists.txt, core/HSPlasmaConfig.cmake.in, net/CMakeLists.txt, net/HSPlasmaNetConfig.cmake.in
If we're building shared libraries (eg HSPlasma.dll and HSPlasmaNet.dll), then downstream users don't need to link against or even know about libraries used internally, such as zlib, png, etc. This fixes our CMake package config files to only search for those dependencies if the downstream user needs to link against them due to building HSPlasma as a static library.
Further, add a missing search for the string_theory library config module.
=> Dependency cleanups for downstream consumers.

core/CMakeLists.txt, core/HSPlasmaConfig.cmake.in, net/CMakeLists.txt, net/HSPlasmaNetConfig.cmake.in
There is a major GOTCHA for exported targets. If an imported library is namespaced (eg `HSPlasma::HSPlasma`), CMake will ensure that the library exists when it is used in a call to `target_link_libraries()`. If an imported library is *not* namespaced (eg `HSPlasma`), then, if the target doesn't exist, CMake will simply pass that library name to the linker and hope for the best. This can lead to confusing errors where, when a non-namespaced imported target is used, configuration can "succeed" but HSPlasma is not actually found correctly. The error doesn't actually emerge until the downstream project attempts to link against the nonexistent HSPlasma.
This change allows downstream users to link against `HSPlasma::HSPlasma` and get a free configure-time check that libHSPlasma has been …
=> Use namespaces for exported targets.

core/ResManager/plResManager.cpp
Reordering keys during write causes ObjIDs to be invalidated by writing pages out. This means that users of tools like PRPShop have to click save on specific PRP files in specific orders. For more information, see pull request #218. The issue fixed here was introduced in ba1d890.
=> Never, never, never sort the keys during a page write.

Python/PRP/Surface/pyLayerSDLAnimation.cpp, Python/PyHSPlasma.pyi, core/PRP/Surface/plLayerAnimation.h
According to the MOULa source code, the correct superclass is `plLayerAnimationBase` and not `plLayerAnimation`. libHSPlasma largely seems to agree - the `CREATABLE` declaration and all of the super method calls already use `plLayerAnimationBase`. The base class declarations saying `plLayerAnimation` were probably by accident.
Someone who knows more than me about old Plasma should double-check this, but I think this change is correct for all Plasma versions - the read/write code has always used `plLayerAnimationBase` as the base class and that apparently worked fine for more than a decade.
=> Fix base class of `plLayerSDLAnimation`

core/PRP/Surface/plMipmap.h, core/Util/plJPEG.cpp
Plasma's plMipmaps store image data in BGR(A) for all uncompressed image types. However, JPEGs are stored as RGB on disk, so we must flip the channels for images that we read in. RLE images are unaffected because they operate on the pixel level. Indeed, the previous behavior would be inconsistent in that Cyan's lossy JPEG mipmaps would appear in RGB while Cyan's RLE mipmaps would appear in BGR.
=> Fix plJPEG image channels order

core/PRP/Surface/plMipmap.cpp, core/PRP/Surface/plMipmap.h, core/Util/plJPEG.cpp, core/Util/plJPEG.h, core/Util/plPNG.cpp, core/Util/plPNG.h
This adds the previously-unimplemented JPEG writer, as well as two new functions to read PNG and JPG files directly into a plMipmap.  The existing readers were intended to be used only when reading from a data stream where the size of the buffer is already known by the calling function, and as such are inconvenient when reading directly from a file.
Depends on #127.
=> Add missing functions to read PNGs and JPGs.

Tools/src/prpgrep.cpp
For example, `prpgrep plSoundBuffer BahroCave_District_YeeshaCave.prp` found no results, even though that page contains many `plSoundBuffer` objects (and other objects that reference them).
Not sure what exactly was wrong with the custom `GetLine` function here, but replacing it with the standard `hsStream::readLine` fixes it.
=> Fix prpgrep not searching some objects properly

Python/PRP/Audio/pyEAXListenerMod.cpp, core/CMakeLists.txt, core/PRP/Audio/plEAXListenerMod.h, core/PRP/Audio/plEAXStructures.h
The header PRP/Audio/plEAXListenerMod.h included an EFX header from 3rdPartyLibs, which isn't part of the public libHSPlasma headers that get installed into the prefix. This made it impossible for downstream projects (e. g. PlasmaShop) to use plEAXListenerMod.h, because the required EFX header is only accessible within libHSPlasma itself.
This PR solves the issue by adding a new header plEAXStructures.h, which contains a copy of the few EAX structures needed by plEAXListenerMod.h. (This is intentionally similar to [plEAXStructures.h in H-uru/Plasma](https://github.com/H-uru/Plasma/blob/HEAD/Sources/Plasma/PubUtilLib/plAudio/plEAXStructures.h).) This header doesn't depend on the OpenAL/EFX headers and can thus be included by downstream projects, but the definitions are compatible with the …
=> Fix plEAXListenerMod.h to be includable from outside libHSPlasma itself

Python/PRP/Surface/pyMipmap.cpp, Python/PyPlasma.h, Python/Stream/pyStream.cpp
As of Python 3.10, all argument codes with the `#` suffix are disabled by default. To re-enable them, we must define `PY_SSIZE_T_CLEAN` and change all of the types from `int` to `Py_ssize_t`. In Python 3.9 and lower, `#` arguments expect the `int` data type by default. The macro is backwards compatible.
=> Fix erroneous `TypeError` from all bindings using the `s#` code.

Python/PyPlasma.h, Python/ResManager/pyResManager.cpp
This resolves compiler warnings about a missing initializer for member `_typeobject::tp_watched` and also fixes a warning about converting a string constant to `char*`.
=> Python 3.12 warning fixes

core/PRP/Geometry/plDrawableSpans.cpp
See CWE's `plGeometrySpans::AdjustBounds()` for the source of this change. Wavesets are flattened at runtime to the water height and are perturbed along the world Z axis. The input mesh, OTOH, conforms to the bottom of the pool. This means that if we simply spit out the bounding box of the input mesh, the resulting bounding box will be too deep in the -Z direction and not contain any of the +Z displacement needed. This means that the waveset could vanish due to culling.
NOTE: A draft because I'd like to test this change against korman.
=> Fix handling of waveset bounding boxes.

.github/workflows/linux-ci.yml, .github/workflows/macos-ci.yml, .github/workflows/windows-ci.yml
Also update to current versions of GHA steps to avoid deprecation warnings.
=> Add building for Python 3.12, x64 in CI

.github/workflows/linux-ci.yml
On ubuntu-24.04 images (which will soon be ubuntu-latest), it seems we need to explicitly install libpng and libjpeg-turbo
=> Fix Linux CI dependencies

CMakeLists.txt, core/Stream/hsStream.cpp, core/Sys/Platform.h
Python uses the same macro name internally, and this results in compiler warnings about redefining it. Since we're updating this, we might as well move to using CMake's endianness detection as opposed to relying on macros being defined (or not defined) in system headers because that has proven unreliable in the past.
=> Avoid WORDS_BIGENDIAN conflict with Python3

Python/PyPlasma.h, Python/Util/pyJPEG.cpp, Python/Util/pyPNG.cpp
Conditionally adds support for Python 3.13, and resolves some other Python warnings about unused init functions.
=> Python 3.13 support

.github/workflows/windows-ci.yml
The windows-2019 runner was removed from GHA about a month ago. Also, we need to test against at least Python 3.13.
=> Remove windows-2019 runners.
