H-uru/libhsplasma

Python/CMakeLists.txt, Python/Module.cpp, Python/PRP/Surface/pyCubicEnvironmap.cpp, Python/PRP/Surface/pyCubicEnvironmap.h, Python/PRP/Surface/pyDynamicEnvMap.cpp, Python/PRP/Surface/pyDynamicEnvMap.h, Python/PRP/Surface/pyRenderTarget.cpp, Python/PRP/Surface/pyRenderTarget.h, Python/PRP/pyCreatableConvert.cpp, Python/ResManager/pyFactory.cpp, core/PRP/Surface/plCubicEnvironmap.h, core/PRP/Surface/plDynamicEnvMap.cpp, core/PRP/Surface/plDynamicEnvMap.h
Creates Python bindings for plRenderTargets, plCubicRenderTargets, plCubicEnvironMaps, plDynamicEnvMaps, and plDynamicCamMaps.
Closes #27.
=> Add PyHSPlasma support for EnvMaps & CamMaps

Python/CMakeLists.txt, Python/Module.cpp, Python/PRP/ConditionalObject/pyConditionalObject.cpp, Python/PRP/ConditionalObject/pyConditionalObject.h, Python/PRP/ConditionalObject/pyVolumeSensorConditionalObject.cpp, Python/PRP/ConditionalObject/pyVolumeSensorConditionalObject.h, Python/PRP/ConditionalObject/pyVolumeSensorConditionalObjectNoArbitration.cpp, Python/PRP/Message/pyArmatureEffectMsg.cpp, Python/PRP/Message/pyArmatureEffectMsg.h, Python/PRP/Physics/pyCollisionDetector.cpp, Python/PRP/Physics/pyCollisionDetector.h, Python/PRP/Physics/pyDetectorModifier.cpp, Python/PRP/Physics/pyDetectorModifier.h, Python/PRP/Physics/pyObjectInVolumeAndFacingDetector.cpp, Python/PRP/Physics/pyObjectInVolumeDetector.cpp, Python/PRP/Physics/pyObjectInVolumeDetector.h, Python/PRP/Physics/pyPanicLinkRegion.cpp, Python/PRP/Physics/pyPickingDetector.cpp, Python/PRP/Physics/pySubworldRegionDetector.cpp, Python/PRP/pyCreatableConvert.cpp, core/PRP/ConditionalObject/plConditionalObject.h, core/PRP/ConditionalObject/plVolumeSensorConditionalObject.h, core/PRP/Message/plArmatureEffectMsg.h, core/PRP/Physics/plObjectInVolumeDetector.h
Lots of logic-type stuff that will enable Korman to do some very basic things like panic link and footstep regions.
=> Moar PyHSPlasma Bindings

Python/PRP/Physics/pyGenericPhysical.cpp, core/Math/hsGeometry3.h, core/PRP/Physics/plGenericPhysical.cpp, core/PRP/Physics/plGenericPhysical.h, core/PRP/Region/hsBounds.cpp, core/PRP/Region/hsBounds.h
These are some GenericPhyical helpers that generate box and sphere bounds for us. Nice for korman.
=> Physics Helpers

Python/PRP/Surface/pyCubicRenderTarget.cpp, core/PRP/Surface/plRenderTarget.h
A general faces getter as suggested by @zrax in #55. I liked the idea for Korman :smile:
=> pyCubicRenderTarget faces getter

Python/PRP/Animation/pyAnimTimeConvert.cpp, Python/PRP/Surface/pyLayerAnimationBase.cpp
=> Fix PyHSPlasma LayerAnimation Issues

Python/CMakeLists.txt, Python/Module.cpp, Python/PRP/Message/pyAnimCmdMsg.cpp, Python/PRP/Message/pyAnimCmdMsg.h, Python/PRP/Message/pyMessageWithCallbacks.cpp, Python/PRP/Message/pyMessageWithCallbacks.h, Python/PRP/Message/pyMsgForwarder.cpp, Python/PRP/Message/pyOneShotMsg.cpp, Python/PRP/Message/pyResponderMsg.cpp, Python/PRP/Message/pyResponderMsg.h, Python/PRP/pyCreatableConvert.cpp, core/PRP/Message/plAnimCmdMsg.h, core/PRP/Message/plOneShotCallbacks.h, core/PRP/Message/plResponderMsg.h
Moar Python bindings. This represents everything needed to export simple "avatar presses a button, then an animation plays" scenarios.
=> OneShot and AnimCmdMsg Python

Python/CMakeLists.txt, Python/Module.cpp, Python/PRP/Message/pyEnableMsg.cpp, Python/PRP/Message/pyEnableMsg.h, Python/PRP/Message/pyTimerCallbackMsg.cpp, Python/PRP/Message/pyTimerCallbackMsg.h, Python/PRP/pyCreatableConvert.cpp
Python bindings for these useful messages in Responders.
=> pyTimerCallbackMsg & pyEnableMsg

Python/PRP/Modifier/pyPythonParameter.cpp
Make the public interface more Pythonic. Who cares that this is internally a union?
=> Duck type pyPythonParameter

Python/CMakeLists.txt, Python/Module.cpp, Python/PRP/Region/pyConvexIsect.cpp, Python/PRP/Region/pySoftVolume.cpp, Python/PRP/Region/pySoftVolume.h, Python/PRP/Region/pySoftVolumeComplex.cpp, Python/PRP/Region/pySoftVolumeIntersect.cpp, Python/PRP/Region/pySoftVolumeInvert.cpp, Python/PRP/Region/pySoftVolumeSimple.cpp, Python/PRP/Region/pySoftVolumeUnion.cpp, Python/PRP/Region/pyVisRegion.cpp, Python/PRP/Region/pyVisRegion.h, Python/PRP/Region/pyVolumeIsect.cpp, Python/PRP/Region/pyVolumeIsect.h, Python/PRP/pyCreatableConvert.cpp, core/Math/hsGeometry3.cpp, core/Math/hsGeometry3.h, core/PRP/Region/plSoftVolume.h, core/PRP/Region/plVisRegion.h, core/PRP/Region/plVolumeIsect.cpp, core/PRP/Region/plVolumeIsect.h
Disclaimer: the pyVolumeIsect support is lazy.
=> Soft Volumes

Python/CMakeLists.txt, Python/Module.cpp, Python/PRP/Audio/pyFadeParams.cpp, Python/PRP/Audio/pySound.cpp, Python/PRP/Audio/pySound.h, Python/PRP/Audio/pyWin32Sound.cpp, Python/PRP/Audio/pyWin32Sound.h, Python/PRP/Audio/pyWin32StaticSound.cpp, Python/PRP/Audio/pyWin32StaticSound.h, Python/PRP/Audio/pyWin32StreamingSound.cpp, Python/PRP/pyCreatableConvert.cpp, core/PRP/Audio/plSound.h, core/PRP/Audio/plWin32Sound.h
Enough bindings to (theoretically) export sounds from Korman.
=> Python Sound Bindings

Python/CMakeLists.txt, Python/Module.cpp, Python/PRP/Surface/pyDistOpacityMod.cpp, Python/PRP/Surface/pyDistOpacityMod.h, Python/PRP/Surface/pyFadeOpacityMod.cpp, Python/PRP/Surface/pyFadeOpacityMod.h, Python/PRP/pyCreatableConvert.cpp, core/PRP/Surface/plDistOpacityMod.cpp, core/PRP/Surface/plDistOpacityMod.h
More bindings needed for Korman.
=> Implement pyDistOpacityMod and pyFadeOpacityMod.

Python/Math/pyVector3.cpp
Needed for the magic bump mapping UVW channels
=> Add PyVector3.normalize()

core/PRP/Physics/plGenericPhysical.cpp, core/PRP/Physics/plPXPhysical.cpp
This matches the proposed format for generic triangle mesh and convex hulls for CWE's plPXPhysical. See also H-uru/Plasma#533
=> Generic PXPhysical

Python/CMakeLists.txt, Python/Module.cpp, Python/PRP/Message/pySwimMsg.cpp, Python/PRP/Message/pySwimMsg.h, Python/PRP/Region/pySimpleRegionSensor.cpp, Python/PRP/Region/pySimpleRegionSensor.h, Python/PRP/Region/pySwimCircularCurrentRegion.cpp, Python/PRP/Region/pySwimDetector.cpp, Python/PRP/Region/pySwimRegion.h, Python/PRP/Region/pySwimRegionInterface.cpp, Python/PRP/Region/pySwimStraightCurrentRegion.cpp, Python/PRP/pyCreatableConvert.cpp, core/PRP/Message/plSwimMsg.h, core/PRP/Region/plSimpleRegionSensor.h, core/PRP/Region/plSwimRegion.h
PyHSPlasma bindings for swim regions
=> Swim bindings

Python/PRP/Surface/pyBitmap.cpp, core/CMakeLists.txt, core/PRP/Surface/plBitmap.cpp, core/PRP/Surface/plBitmap.h, core/PRP/Surface/plMipmap.cpp, core/PRP/Surface/plMipmap.h, core/Util/plJPEG.cpp, core/Util/plJPEG.h, core/Util/plPNG.cpp, core/Util/plPNG.h
This adds support for H-uru/Plasma#356 in HSPlasma's plMipmap readers and writers.
=> Support PNG textures

core/Stream/plEncryptedStream.cpp
Fixes crashes in H-uru/PlasmaShop#33
=> Don't use readStr on potentially binary data

Tools/src/PlasmaSum.cpp
Adds a missing include to PlasmaSum that prevented the program from compiling.
=> Fix missing PlasmaSum include

core/PRP/Animation/plController.cpp, core/PRP/Animation/plLeafController.cpp, core/PRP/Animation/plLeafController.h
Incorrect plController export reported by @dpogue https://github.com/H-uru/korman/issues/78#issuecomment-336614840
=> Correctly encapsulate UruSP key controllers

CMakeLists.txt, core/Stream/hsRAMStream.cpp, core/Stream/hsRAMStream.h, core/Sys/plUuid.cpp, core/Sys/plUuid.h, net/auth/pnAuthClient.cpp, net/auth/pnVaultNode.cpp, net/auth/pnVaultNode.h, net/crypt/pnRC4.cpp, net/file/pnFileClient.cpp, net/game/pnGameClient.cpp, net/gate/pnGateKeeperClient.cpp, net/pnNetMsg.cpp, net/pnNetMsg.h, net/pnSocket.cpp
... some of which caused issues with [H-uru/MoulKI](https://github.com/H-uru/MoulKI)
=> Fix several ASan/UBSan issues in HSPlasmaNet

net/pnNetMsg.h
=> Add missing include for memcpy/memset

core/Sys/Platform.h, net/crypt/pnSha1.cpp
Based on https://github.com/H-uru/dirtsand/pull/130
=> Add hand-rolled SHA-0 hash to work around its removal in OpenSSL 1.1.

core/PRP/Animation/plAnimPath.h
Fixes random heap garbage being written to the disk, unless you feel like being explicit.
=> Fix plAnimPath zero init

Tools/src/PlasmaSum.cpp
=> Fix PlasmaSum tool not creating empty sum files.

Python/Stream/pyEncryptedStream.cpp
Thanks to @Hoikas for finding this cause of a crash!
=> Remove inappropriate reference decrement.

CMakeLists.txt, Python/Module.cpp, Tools/src/PlasmaSum.cpp, Tools/src/PrpPack.cpp, Tools/src/PyPack.cpp, Tools/src/prcc.cpp, Tools/src/prcdc.cpp, Tools/src/prpmod.cpp, core/Debug/hsExceptions.hpp, core/Debug/plDebug.cpp, core/PRP/Audio/plSoundBuffer.cpp, core/PRP/GUI/pfGUITextBoxMod.cpp, core/PRP/plPageInfo.cpp, core/SDL/plStateDescriptor.cpp, core/SDL/plStateVariable.cpp, core/Stream/hsElfStream.cpp, core/Stream/hsStream.cpp, core/Stream/hsTokenStream.cpp, core/Stream/pfPrcParser.h, core/Sys/plUuid.cpp, core/Util/hsSumFile.h, core/Util/plMD5.cpp, core/Vault/plServerGuid.cpp, net/pnSocket.cpp
We have depended on string_theory 2.0 for about a year now, so there's no need to keep carrying the legacy ST1.0 support around.
=> Clean up use of deprecated string_theory 1.x APIs.

Python/PRP/Surface/pyMipmap.cpp, core/PRP/Geometry/plSharedMesh.h
Fixes two minor issues found while working on other code.
=> Miscellaneous cleanup.

Python/CMakeLists.txt, Python/Module.cpp, Python/PyPlasma.h, Python/SDL/pySDL.h, Python/SDL/pySDLMgr.cpp, Python/SDL/pyStateDescriptor.cpp, Python/SDL/pyVarDescriptor.cpp, core/SDL/plSDLMgr.cpp, core/SDL/plSDLMgr.h
This adds just enough SDL to PyHSPlasma for one to be able to poke around the SDL files.
=> PyHSPlasma SDL

core/Sys/Platform.h
We already have a 64-bit swap...  Let's use it.
=> Simplify ENDSWAPD

CMakeLists.txt, appveyor.yml, core/PRP/KeyedObject/plKey.h, core/PRP/Surface/plFont.h, core/PlasmaDefs.h
=> Restore compatibility with MSVC 2013.

Python/PyPlasma.h
=> Python 3.8 compatibility

core/PRP/Geometry/plGeometrySpan.h
This should match the output from PlasmaMax.
=> Default min and max distances to -1

Python/CMakeLists.txt, Python/Module.cpp, Python/PRP/Message/pyWarpMsg.cpp, Python/PRP/Message/pyWarpMsg.h, Python/PRP/pyCreatableConvert.cpp, core/CMakeLists.txt, core/PRP/Message/plWarpMsg.cpp, core/PRP/Message/plWarpMsg.h, core/ResManager/plFactory.cpp
Adds plWarpMsg and associated Python bindings.
=> Add plWarpMsg and pyWarpMsg.

core/CMakeLists.txt, core/PRP/Animation/plWindBoneMod.cpp, core/PRP/Animation/plWindBoneMod.h, core/ResManager/plFactory.cpp
Sadly even with knowing what the structure of the data is and knowing roughly how the values are used, it's still unclear what they actually represent :(
As far as I can tell, there is only a single example of a WindBoneMod in Myst V, used for the Laki'ahn trees.
=> Stub out read/write support for plWindBoneMod

README.md, libhsplasma-vcpkg.cmake
Also removes some obsolete info from the README.
=> Add a vcpkg triplet file and update README to describe its use.

core/PRP/Animation/plWindBoneMod.cpp, core/PRP/Animation/plWindBoneMod.h
=> WindBoneMod fixes

core/PRP/Geometry/plSpanTemplate.cpp
=> Fix plSpanTemplate PRC vert color parsing

core/PRP/Geometry/plGeometrySpan.cpp
=> Add missing GeoSpan members to PRC

core/CMakeLists.txt, net/CMakeLists.txt
Fixes PlasmaShop CI regression.
=> Actually install the new generated export headers.

core/ResManager/plKeyCollector.cpp
=> Fix invalid format string.

Python/ResManager/pyResManager.cpp
Yo dawg, I hear you like negation with your negation, so here's a commit negating that negation of a negation, yo.
=> Fix pyResManager.optimizeKeys() type detection.

Python/CMakeLists.txt, Python/PRP/pyCreatableConvert.cpp
... So that ZLZ can finally import clothing items.
(@Hoikas, when preparing for the next release of Korman, could the redistributed HSPlasma.pyd be rebuilt to include this ? Thanks !)
=> Python: expose plClothingItem class

core/PRP/Particle/plParticleGenerator.cpp
=> Fix PRC parsing of Particle Source params

.github/workflows/macos-ci.yml
=> Update GCC for macOS CI to GCC 12.

Python/PRP/Modifier/pyPythonParameter.cpp, core/PRP/Modifier/plPythonFileMod.cpp, core/PRP/Modifier/plPythonFileMod.h
=> Add new PFM Attribute for plLayers.

net/auth/pnAuthClient.cpp
=> Remove orphaned variable.
